Feature/header fillet
renatoam/amc-services pull request #19
Opened 2022-04-12 01:37 UTC by CardosoAdriel

2022-04-13 01:06 UTC, renatoam commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +  height: 72px;
Evite usar pixel como unidade de medida. Use sempre tamanhos relativos para projetos que visam responsividade. Nesse caso, use `rem`.

2022-04-13 01:07 UTC, renatoam commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +export const WrapFillet = styled.div`
Aqui, entendo que sua intenção é se referir a um elemento que vá envolver (a wrapper) outros elementos, nesse caso, chamamos de **wrapper** (envelope, invólucro) ou **container**.

2022-04-13 01:08 UTC, renatoam commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +  max-width: 1440px;
Mesma regrinha dos tamanhos relativos.

2022-04-13 01:09 UTC, renatoam commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +export const WrapContentFillet = styled.div`
Evite usar tags não semânticas, como `div`. Procure sempre trabalhar com semântica quando possível, isso é fundamental para SEO e Acessibilidade. Nesse caso, `section`.

2022-04-13 01:09 UTC, renatoam commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +  gap: 20px;
Tamanhos relativos.

2022-04-13 18:32 UTC, CardosoAdriel commented on src/modules/shared/components/molecules/Fillet/index.tsx
> +export default function FilletWrapper() {
Corrected

2022-04-13 18:32 UTC, CardosoAdriel commented on src/modules/shared/components/molecules/Fillet/index.tsx
> +  return (
Corrected

2022-04-13 18:35 UTC, CardosoAdriel commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +  height: 72px;
Corrected

2022-04-13 19:07 UTC, CardosoAdriel commented on src/modules/shared/components/molecules/Fillet/index.tsx
> +            {item.id === 1 ? (
Corrected

2022-04-13 20:02 UTC, CardosoAdriel commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +export const WrapFillet = styled.div`
Corrected

2022-04-13 20:13 UTC, CardosoAdriel commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +  max-width: 1440px;
Corrected

2022-04-13 20:13 UTC, CardosoAdriel commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +export const WrapContentFillet = styled.div`
Corrected

2022-04-13 21:58 UTC, renatoam requested changes
Somente nomenclaturas

2022-04-13 21:58 UTC, renatoam commented on src/modules/shared/components/molecules/Fillet/index.tsx
> +      <WraperFillet>
Aqui vão dois pontos:

- "Wrapper", com dois p
- Components são como classes, tbm temos que manter padrão. Nesse caso, se vc usou `FilletContainer`, use `FilletWrapper`

2022-04-13 21:58 UTC, renatoam commented on src/modules/shared/components/molecules/Fillet/styles.ts
> +export const WraperFillet = styled.section`
Wrapper, mas já comentei ali em cima

2022-04-13 21:58 UTC, renatoam commented on src/modules/shared/constants/fillet.tsx
> +interface textFillet {
Types e Interface devem iniciar com letra maiúscula.

2022-04-13 22:45 UTC, renatoam approved these changes
Done!

2022-04-13 22:46 UTC, renatoam submitted a review, later dismissed

2022-04-14 00:38 UTC, renatoam approved these changes

2022-04-14 00:39 UTC, renatoam commented
# [Codecov](https://codecov.io/gh/renatoam/amc-services/pull/19?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo) Report
> Merging [#19](https://codecov.io/gh/renatoam/amc-services/pull/19?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo) (9dd336c) into [develop](https://codecov.io/gh/renatoam/amc-services/commit/631a277b4d514ae0d2296a6b6673463073689fc4?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo) (631a277) will **not change** coverage.
> The diff coverage is `100.00%`.

```diff
@@            Coverage Diff            @@
##           develop       #19   +/-   ##
=========================================
  Coverage   100.00%   100.00%           
=========================================
  Files            1        13   +12     
  Lines            1        55   +54     
  Branches         0         3    +3     
=========================================
+ Hits             1        55   +54     
```


| [Impacted Files](https://codecov.io/gh/renatoam/amc-services/pull/19?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo) | Coverage Δ | |
|---|---|---|
| [...rc/modules/shared/components/atoms/Image/index.tsx](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvSW1hZ2UvaW5kZXgudHN4) | `100.00% <100.00%> (ø)` | |
| [...rc/modules/shared/components/atoms/Image/styles.ts](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvSW1hZ2Uvc3R5bGVzLnRz) | `100.00% <100.00%> (ø)` | |
| [src/modules/shared/components/atoms/Link/index.tsx](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvTGluay9pbmRleC50c3g=) | `100.00% <100.00%> (ø)` | |
| [src/modules/shared/components/atoms/List/index.tsx](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvTGlzdC9pbmRleC50c3g=) | `100.00% <100.00%> (ø)` | |
| [src/modules/shared/components/atoms/List/styles.ts](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvTGlzdC9zdHlsZXMudHM=) | `100.00% <100.00%> (ø)` | |
| [...modules/shared/components/atoms/ListItem/index.tsx](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvTGlzdEl0ZW0vaW5kZXgudHN4) | `100.00% <100.00%> (ø)` | |
| [...modules/shared/components/atoms/ListItem/styles.ts](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvTGlzdEl0ZW0vc3R5bGVzLnRz) | `100.00% <100.00%> (ø)` | |
| [src/modules/shared/components/atoms/Text/index.tsx](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvVGV4dC9pbmRleC50c3g=) | `100.00% <100.00%> (ø)` | |
| [src/modules/shared/components/atoms/Text/styles.ts](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvYXRvbXMvVGV4dC9zdHlsZXMudHM=) | `100.00% <100.00%> (ø)` | |
| [...dules/shared/components/molecules/Header/index.tsx](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo#diff-c3JjL21vZHVsZXMvc2hhcmVkL2NvbXBvbmVudHMvbW9sZWN1bGVzL0hlYWRlci9pbmRleC50c3g=) | `100.00% <100.00%> (ø)` | |
| ... and [4 more](https://codecov.io/gh/renatoam/amc-services/pull/19/diff?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/renatoam/amc-services/pull/19?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/renatoam/amc-services/pull/19?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo). Last update [68802bb...9dd336c](https://codecov.io/gh/renatoam/amc-services/pull/19?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Renato+Melo).

2022-04-14 00:41 UTC, merged